appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RpItC99uXtH/3WS0LSCtuW8zNdNu+ZF6IATwim3A4n9Y5E5uZouCO8HbbeIOgDudbfS+Dr+suwI5kQVJOUWMURkN7qBrAoIJ8U7Ulso7+IzfZgQJ7JSJDj9ICOXorRW3Q66JK48IcVqxzz+gki/kNKK7IGhcGn8ZVzYWA4lj0KVJffKcIWcfE+2fcQAO33w7WFrYAdXA+fFt7jlaVFqsPGddk8QBZsFrtpnDToGQSsCV21ijo554ccb5e1MQ+2/i7FL1/Wmtl0/6MYihqUsM7I0MCn60qI/E8Pn6NKxXD4SSQIwqX874McgJsw3U/Kqw31QwrwJuUjh3+t/oU+RUW+VqEwAnGrRACvshsnrpVt5PzKHwmdKPeLB1MLGBkaMSVKdNUc5MwXHOutwbdrtVVaNlMZQRAho5NgQ2l0DPpizbmRFpBLWnMv0ttbfpH6Kq2ORvLpR69tgzHQfAv6xG6v7Nb0Wi0s1atn5gc/ejGe9d1lBgzc8RoAPrVo7lgA1W3yWFvMtrAuRW1TrnrXBrAvGHQw3iFpXcC1Tek4hlXasyRsYfYngxsZdKoEI1Qz/M/4yAn6eIT+u70jXGRJ1dZRQ4ZfPdZJSybDBW2IQE1e4VaCSloSXfjzqMlTcLi2di62eIPfkHg6TxUklqkwBsYguPNBBmX6W3xQCDugkLyac=}
bot:
  automerge: true
